### PR TITLE
Added pygame install on mac

### PR DESCRIPTION
**Pull request by makokal**
Added instructions for installing pygame on mac via anaconda

### CODE REVIEW

**Comment by ntasfi** [comment]
Have you tested it on a fresh system?

**Comment by EderSantana** [comment]
this works on my mac!!! Thanks 👍

**Comment by ntasfi** [comment]
Awesome, ty @makokal and @EderSantana

**Comment by makokal** [comment]
Awesome, sorry I was late responding. Yes I did try it on y fresh system

**Comment by ntasfi** [comment]
No worries, thanks for the PR :)

**Pull request merged**
