### PR TITLE
Python 3 support w/ tests

### PR DESCRIPTION
**Pull request by gregretkowski**
This PR has the changes to support running under Python 3. I have also included a tests/test_ple.py script which can be used to test all the games that I ported. Not sure if I broke anything during the process as there were a lot of changes to be made, but I did verify all the games in the test launch and run in both Python 2 and Python 3.

With these changes I also attempted to split out the doom games from the non-doom; that is, the library will run the non-doom games w/o py_doom being installed.

### CODE REVIEW

**Comment by ntasfi** [comment]
Hey Greg, thanks for the PR! I'll review it this weekend.

**Comment by zergylord** [comment]
Thanks so much for the port! I just tried out your branch, and while I can now import ple and pong in python3, Pong() causes the following error:
`  File "<stdin>", line 1, in <module>
  File "/home/zergylord/PyGame-Learning-Environment/ple/games/pong.py", line 168, in __init__
    base.PyGameWrapper.__init__(self, width, height, actions=actions)
NameError: name 'base' is not defined
`
I think its another of those cases were python3 is confused by python2 style imports, but that is just a hunch.

**Comment by gregretkowski** [comment]
Fix pushed. Let me know if you notice other broken games.

On November 17, 2016 10:05:01 AM PST, zergylord <notifications@github.com> wrote:
>Thanks so much for the port! I just tried out your branch, and while I
>can now import ple and pong in python3, Pong() causes the following
>error:
>`  File "<stdin>", line 1, in <module>
>File "/home/zergylord/PyGame-Learning-Environment/ple/games/pong.py",
>line 168, in __init__
>    base.PyGameWrapper.__init__(self, width, height, actions=actions)
>NameError: name 'base' is not defined
>`
>I think its another of those cases were python3 is confused by python2
>style imports, but that is just a hunch.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ntasfi/PyGame-Learning-Environment/pull/23#issuecomment-261321865

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ntasfi** [comment]
Looks good to me. Merged. Thanks again @gregretkowski!

**Pull request merged**
