### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by EderSantana**
Please check if that works for you and let me know if I have to change anything.

### CODE REVIEW

**Comment by EderSantana** [comment]
btw, how do I squash commits into one?

**Comment by ntasfi** [comment]
`git rebase -i HEAD~10` then you select the commits you want to squash by changing `pick` to `s` or `squash`

**Comment by ntasfi** [comment]
I think GitHub does it now for you when you merge?

**Comment by EderSantana** [comment]
I heard they do.. Maybe you want to check the repo configs to be sure

**Comment by ntasfi** [comment]
Its enabled, I can try it

**Comment by ntasfi** [comment]
awesome, it worked. ty for the PR :+1:

**Pull request merged**
